# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
        exclude: ^images/3-vscode/vscode-config/settings-locale.json$
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      # AWS credentials checker: https://www.unixdaemon.net/cloud/preventing-aws-creds-in-git-with-pre-commit/
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
        # remark: is usually done in Dockerfiles later to add such permissions for the containers
        # - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id:
          prettier
          # VSCode's normalized settings.json is not recognized as proper, fine-styled JSON
          # VSCode's normalized settings-locale.json is not recognized as proper due to dev comments in it
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
