version: "3.7"
# earliest version w/ feature "build target" is Docker Compose's v3.4
# source: https://docs.docker.com/compose/compose-file/compose-file-v3/#target

services:
  ###########################################################################
  #     ___        ______     ___     _  _____         ____ _     ___       #
  #    / \ \      / / ___|   ( _ )   | |/ ( _ ) ___   / ___| |   |_ _|___   #
  #   / _ \ \ /\ / /\___ \   / _ \/\ | ' // _ \/ __| | |   | |    | |/ __|  #
  #  / ___ \ V  V /  ___) | | (_>  < | . \ (_) \__ \ | |___| |___ | |\__ \  #
  # /_/   \_\_/\_/  |____/   \___/\/ |_|\_\___/|___/  \____|_____|___|___/  #
  #                                                                         #
  ###########################################################################

  # rather late versions
  utils-w-aws-k8s-cli-latest-versions:
    image: utils-w-aws-k8s-cli:awscli-v2.8.2-k8scli-v1.22.10-and-helm-v3.10.0
    build:
      context: 1-utils-w-aws-and-k8s-clis
      args:
        BASE_IMAGE: ubuntu:20.04
        AWS_CLI_VERSION: 2.8.2
        AWS_CLI_CHECKSUM: ca0e766fe70b14c1f7e2817836acf03e4a3e6391b7ed6a464282c5b174580b9a
        K8S_CLI_VERSION: 1.22.10
        HELM_VERSION: 3.10.0
        HELM_DOWNLOAD_CHECKSUM: bf56beb418bb529b5e0d6d43d56654c5a03f89c98400b409d1013a33d9586474

  # 2nd latest versions
  utils-w-aws-k8s-cli-almost-latest-versions:
    image: utils-w-aws-k8s-cli:awscli-v2.7.24-k8scli-v1.25.2-and-helm-v3.10.0
    build:
      context: 1-utils-w-aws-and-k8s-clis
      args:
        BASE_IMAGE: ubuntu:20.04
        AWS_CLI_VERSION: 2.7.24
        AWS_CLI_CHECKSUM: 5a0290f93aa5ce79628fd66b8c13397326900eeb51b188ac68ed40ba2a7025c4
        K8S_CLI_VERSION: 1.25.2
        HELM_VERSION: 3.10.0
        HELM_DOWNLOAD_CHECKSUM: bf56beb418bb529b5e0d6d43d56654c5a03f89c98400b409d1013a33d9586474
